---

- hosts: all
  become: true
  pre_tasks:

  - name: dnf and epel-release download
    yum:
      name:
        - epel-release
        - dnf
    when: ansible_distribution == "CentOS"

  - name: Remote CentOS server Update and Upgrade
    dnf:
      update_cache: yes
      name: "*"
      state: latest
    when: ansible_distribution == "CentOS"

  - name: Ubuntu Servers fixing by Dpkg
    shell: |
      dpkg --configure -a
    when: ansible_distribution == "Ubuntu"

  - name: Remote Ubuntu server Update and Upgrade
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: ubuntu
  become: true
  roles:
    - ubuntu

- hosts: centos
  become: true
  roles:
    - centos
